/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.openviz.dev/apimachinery/apis/openviz/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePersesDashboards implements PersesDashboardInterface
type FakePersesDashboards struct {
	Fake *FakeOpenvizV1alpha1
	ns   string
}

var persesdashboardsResource = v1alpha1.SchemeGroupVersion.WithResource("persesdashboards")

var persesdashboardsKind = v1alpha1.SchemeGroupVersion.WithKind("PersesDashboard")

// Get takes name of the persesDashboard, and returns the corresponding persesDashboard object, and an error if there is any.
func (c *FakePersesDashboards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PersesDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(persesdashboardsResource, c.ns, name), &v1alpha1.PersesDashboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PersesDashboard), err
}

// List takes label and field selectors, and returns the list of PersesDashboards that match those selectors.
func (c *FakePersesDashboards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PersesDashboardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(persesdashboardsResource, persesdashboardsKind, c.ns, opts), &v1alpha1.PersesDashboardList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PersesDashboardList{ListMeta: obj.(*v1alpha1.PersesDashboardList).ListMeta}
	for _, item := range obj.(*v1alpha1.PersesDashboardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested persesDashboards.
func (c *FakePersesDashboards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(persesdashboardsResource, c.ns, opts))

}

// Create takes the representation of a persesDashboard and creates it.  Returns the server's representation of the persesDashboard, and an error, if there is any.
func (c *FakePersesDashboards) Create(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.CreateOptions) (result *v1alpha1.PersesDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(persesdashboardsResource, c.ns, persesDashboard), &v1alpha1.PersesDashboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PersesDashboard), err
}

// Update takes the representation of a persesDashboard and updates it. Returns the server's representation of the persesDashboard, and an error, if there is any.
func (c *FakePersesDashboards) Update(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.UpdateOptions) (result *v1alpha1.PersesDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(persesdashboardsResource, c.ns, persesDashboard), &v1alpha1.PersesDashboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PersesDashboard), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePersesDashboards) UpdateStatus(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.UpdateOptions) (*v1alpha1.PersesDashboard, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(persesdashboardsResource, "status", c.ns, persesDashboard), &v1alpha1.PersesDashboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PersesDashboard), err
}

// Delete takes name of the persesDashboard and deletes it. Returns an error if one occurs.
func (c *FakePersesDashboards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(persesdashboardsResource, c.ns, name, opts), &v1alpha1.PersesDashboard{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePersesDashboards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(persesdashboardsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PersesDashboardList{})
	return err
}

// Patch applies the patch and returns the patched persesDashboard.
func (c *FakePersesDashboards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PersesDashboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(persesdashboardsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PersesDashboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PersesDashboard), err
}
