/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.openviz.dev/apimachinery/apis/openviz/v1alpha1"
	scheme "go.openviz.dev/apimachinery/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PersesDashboardsGetter has a method to return a PersesDashboardInterface.
// A group's client should implement this interface.
type PersesDashboardsGetter interface {
	PersesDashboards(namespace string) PersesDashboardInterface
}

// PersesDashboardInterface has methods to work with PersesDashboard resources.
type PersesDashboardInterface interface {
	Create(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.CreateOptions) (*v1alpha1.PersesDashboard, error)
	Update(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.UpdateOptions) (*v1alpha1.PersesDashboard, error)
	UpdateStatus(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.UpdateOptions) (*v1alpha1.PersesDashboard, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PersesDashboard, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PersesDashboardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PersesDashboard, err error)
	PersesDashboardExpansion
}

// persesDashboards implements PersesDashboardInterface
type persesDashboards struct {
	client rest.Interface
	ns     string
}

// newPersesDashboards returns a PersesDashboards
func newPersesDashboards(c *OpenvizV1alpha1Client, namespace string) *persesDashboards {
	return &persesDashboards{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the persesDashboard, and returns the corresponding persesDashboard object, and an error if there is any.
func (c *persesDashboards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PersesDashboard, err error) {
	result = &v1alpha1.PersesDashboard{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("persesdashboards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PersesDashboards that match those selectors.
func (c *persesDashboards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PersesDashboardList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PersesDashboardList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("persesdashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested persesDashboards.
func (c *persesDashboards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("persesdashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a persesDashboard and creates it.  Returns the server's representation of the persesDashboard, and an error, if there is any.
func (c *persesDashboards) Create(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.CreateOptions) (result *v1alpha1.PersesDashboard, err error) {
	result = &v1alpha1.PersesDashboard{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("persesdashboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(persesDashboard).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a persesDashboard and updates it. Returns the server's representation of the persesDashboard, and an error, if there is any.
func (c *persesDashboards) Update(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.UpdateOptions) (result *v1alpha1.PersesDashboard, err error) {
	result = &v1alpha1.PersesDashboard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("persesdashboards").
		Name(persesDashboard.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(persesDashboard).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *persesDashboards) UpdateStatus(ctx context.Context, persesDashboard *v1alpha1.PersesDashboard, opts v1.UpdateOptions) (result *v1alpha1.PersesDashboard, err error) {
	result = &v1alpha1.PersesDashboard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("persesdashboards").
		Name(persesDashboard.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(persesDashboard).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the persesDashboard and deletes it. Returns an error if one occurs.
func (c *persesDashboards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("persesdashboards").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *persesDashboards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("persesdashboards").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched persesDashboard.
func (c *persesDashboards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PersesDashboard, err error) {
	result = &v1alpha1.PersesDashboard{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("persesdashboards").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
