/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.openviz.dev/apimachinery/apis/ui/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeDashboardGroups implements DashboardGroupInterface
type FakeDashboardGroups struct {
	Fake *FakeUiV1alpha1
}

var dashboardgroupsResource = schema.GroupVersionResource{Group: "ui.openviz.dev", Version: "v1alpha1", Resource: "dashboardgroups"}

var dashboardgroupsKind = schema.GroupVersionKind{Group: "ui.openviz.dev", Version: "v1alpha1", Kind: "DashboardGroup"}

// Create takes the representation of a dashboardGroup and creates it.  Returns the server's representation of the dashboardGroup, and an error, if there is any.
func (c *FakeDashboardGroups) Create(ctx context.Context, dashboardGroup *v1alpha1.DashboardGroup, opts v1.CreateOptions) (result *v1alpha1.DashboardGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dashboardgroupsResource, dashboardGroup), &v1alpha1.DashboardGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DashboardGroup), err
}
